### ISSUE TITLE
Upload media not work

### ISSUE THREAD

**Issue by pcomp96** [harmonyzhang/whatsapp-business-java-sdk#5]
Hi @harmonyzhang,
First of all, thank you for this repository, is very useful.

---
I implemented everything easily and now I'm doing the testing phase, a week ago I launched the tests for the _uploadMedia_ and it worked. Today launching a test with the average upload, it failed. 
The exception thrown comes from the library 

`java.lang.NoSuchMethodError: okhttp3.MultipartBody.create([BLokhttp3/MediaType;)Lokhttp3/RequestBody;
 at com.whatsapp.api.impl.WhatsappBusinessCloudApi.uploadMedia([WhatsappBusinessCloudApi.java:73]`

[Go to WhatsappBusinessCloudApi.uploadMedia ](https://github.com/harmonyzhang/whatsapp-business-java-sdk/blob/6a5e244c1e13a8ff737687c2857cc14108024ec9/src/main/java/com/whatsapp/api/impl/WhatsappBusinessCloudApi.java#LL73C4-L73C99)

```java
  public UploadResponse uploadMedia(String phoneNumberId, String fileName, FileType fileType, byte[] file) {

        RequestBody requestFile = MultipartBody.create(file, MediaType.parse(fileType.getType()));

           .......
    }
```
 _From the source code I see that there is no method with this signature:_ 
` MultipartBody.create(byte[] file, MediaType fileType);`

---
_There is a method that has this signature and I think you need to change this line so as not to throw this exception._

![code](https://user-images.githubusercontent.com/80928861/236160401-182d728a-354d-452f-a20a-7eddcc97ea98.png)

For the solution I think it would be enough just to reverse the parameters passed to the method.

I hope you find this observation useful, I remain available for clarification .. Thank you! 😉

**Comment by harmonyzhang** [comment]
感谢您提供的反馈，问题已经在版本V1.0.0-SNAPSHOT中修复了
